# Generated by Django 5.1.3 on 2026-08-17 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('geo_provider_used', models.CharField(blank=True, max_length=50)),
                ('honeypot_triggered', models.BooleanField(default=False)),
                ('side_effect_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.tenant')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='widgets.widget')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'widget', '-created_at'], name='submissions_tenant__a72fa1_idx')],
            },
        ),
    ]
