# Generated by Django 5.1.3 on 2026-08-17 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('signup_form', 'Signup form'), ('cta', 'Call to action'), ('popover', 'Popover')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('form_fields', models.JSONField(default=list)),
                ('button_text', models.CharField(default='Submit', max_length=100)),
                ('display_options', models.JSONField(default=dict)),
                ('bundle_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='widgets_wid_tenant__581313_idx')],
            },
        ),
    ]
